export { default as Banner } from './Banner'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Location } from './Location'
export { default as Navbar } from './Navbar'
export { default as Portfolio } from './Portfolio'
export { default as Pricing } from './Pricing'
export { default as Ratings } from './RatingTab/Ratings'
